### ISSUE TITLE
Upgrade to styled-components v4

### ISSUE THREAD

**Issue by aabenoja** [WTW-IM/es-components#198]
See the announcement [here](https://medium.com/styled-components/announcing-styled-components-v4-better-faster-stronger-3fe1aba1a112).

[styled-components changelog](https://github.com/styled-components/styled-components/blob/develop/CHANGELOG.md)

## Todo
* [ ] replace `injectGlobal` with `createGlobalStyle`
* [ ] replace `.extend()` with `styled`
* [ ] replace [`withTheme` hoc](https://github.com/WTW-IM/es-components/issues/198#issuecomment-420025855)

The above may not be final

**Comment by Darrken** [comment]
Also in the latest beta: "Expose ThemeConsumer component, the 'consumer' render prop component from the React.createContext API if people are interested in using it rather than / in addition to the withTheme HOC"

Unsure if it's something that we would want to use or not.

**Comment by Darrken** [comment]
Looks like they also converted some of their internals to `PureComponent` in 4.0, so that may affect our ability to use it at this time.

**Comment by aabenoja** [comment]
> Also in the latest beta: "Expose ThemeConsumer component, the 'consumer' render prop component from the React.createContext API if people are interested in using it rather than / in addition to the withTheme HOC"

That doesn't sound so bad. So long as components created with `styled` continue to pull from that context updating our `withTheme` usage "should" not pose a problem.

> Looks like they also converted some of their internals to PureComponent in 4.0, so that may affect our ability to use it at this time.

Sounds like our legacy app has yet another reason to be updated, but yes, the usage of `PureComponent` is going to cause problems.

**Comment by aabenoja** [comment]
So we don't have to worry about the `PureComponent` usage with #204.

**Comment by Darrken** [comment]
Closed with #232
