### ISSUE TITLE
Investigate Dependency Updates

### ISSUE THREAD

**Issue by aabenoja** [WTW-IM/es-components#199]
Besides babel 7 we have 5 outdated dependencies per [david-dm](https://david-dm.org/wtw-im/es-components?path=packages%2Fes-components), two of them we have pinned instead of floated.

## Todo
* [ ] `react-popper` has been overhauled to use render props
* [ ] `react-text-mask` used `PureComponent`, which breaks our downstream projects
* [ ] `text-mask-addons`

~~`react-text-mask` and `text-mask-addons` are not floated dependencies. Fortunately we are only a couple versions behind and none of them are major. Can we float them to pull the latest `v5` and `v3`, respectively?
`react-animate-height` and `uncontrollable` are far out of date. How much do we need to fix to get this updated?
`react-popper` released `1.0.2`. It doesn't look like there are any "breaking" changes per the [`v1` release notes](https://github.com/FezVrasta/react-popper/releases/tag/v1.0.0)~~

**Comment by Darrken** [comment]
All good questions. I know at least one of those will require some significant refactoring in a component or two to get them working. I can start digging into these.

**Comment by aabenoja** [comment]
Well, that's concerning. So it's currently floated in the `package.json`. The `package-lock.json` is never included in the npm package, so it's worrying that this is what users are seeing when they pull our package down:

![screen shot 2018-09-06 at 3 57 57 pm](https://user-images.githubusercontent.com/3229671/45187463-ef013780-b1ed-11e8-979c-50fda6dec861.png)

**Comment by Darrken** [comment]
I've locked down that version in #192 for now.

**Comment by aabenoja** [comment]
Updated the top first post with a todo. `text-mask-addons` has been omitted for the time being since it's tied to `react-text-mask`. The last unknown at this point is `uncontrollable`.

**Comment by Darrken** [comment]
I've got a PR for uncontrollable inbound. It needed enzyme-adapter-react-16 updated as well before it worked.

I started updating other things and styleguidist blows up with the latest and won't display most of the sections anymore... I haven't figured out why yet.

**Comment by aabenoja** [comment]
I've updated the list of outdated packages now that we're on `v19`.
